### ISSUE TITLE
When I use it in VM, the “database.db” can't be created correctly

### ISSUE THREAD

**Issue by g0mxxm** [WithSecureLabs/GarbageMan#4]
Whatever I use "Attach" or "Execute" to operate a .NET program. When I click the "start" buttom ,  The phrase that is "Creating Database, please wait..."  will flash and there will be no other reaction. Can u tell me how to solve this problem, Thank u very much bro!!!

**Comment by turkja** [comment]
Could be missing runtime libraries. You need .NET 5.0 desktop runtime for both amd64 and x86. Maybe the command line tools are more verbose. Please try bin\arch\GM.exe --pid <pid>.

**Comment by g0mxxm** [comment]
> Could be missing runtime libraries. You need .NET 5.0 desktop runtime for both amd64 and x86. Maybe the command line tools are more verbose. Please try bin\arch\GM.exe --pid .

Thank u very much bro, u're right,! The target program is x86, but I only install the amd64 .NET. When  the app‘s GUI comes out realistically, I mistakenly thought I had everything ready！When I installed the x86 .NET，the app work properly. Thank u again bro, this tool is awesome!!!

**Comment by turkja** [comment]
Nice!
